### ISSUE TITLE
Question about project dialog

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#13]
Not sure is this normal when the 1st time I launch `project_dialog.UI()`. because type, image format, repository, and structure are empty. should we set anything to config.py in order to have the default setting before launch `project_dialog.UI()`?
![project_dialog](https://user-images.githubusercontent.com/7018625/29071354-c8126918-7c75-11e7-80d1-3b1df2af7940.jpg)

**Comment by eoyilmaz** [comment]
No, no need to set anything in the ``config.py``. Just enter something for the Type field like "Commercial", and for the ImageFormat, Repository and Structure fields you can use the "New.." button to create new instances.

**Comment by tws0002** [comment]
I don't understand how does the structure work!! 
![howtocreateprjstructure](https://user-images.githubusercontent.com/7018625/29131778-86f08b36-7d60-11e7-9fdf-2eda55777f59.jpg)
in the Create Structure dialog, there is 2 column one is Templates from DB and another is Selected Templates. which means I need to create a studio project template structure save it to DB in order to display in the Templates From DB column? (if yes how can I create a template project structure?)
or there is a default template I can straight away use to kickstart a project?

I have tried using Version Creator to create project structure, but seems like nothing create after I do this step!! 
![vc_createprjstructure](https://user-images.githubusercontent.com/7018625/29132079-93ecb020-7d61-11e7-9ecc-90ac2653c265.jpg)

**Comment by eoyilmaz** [comment]
Oh yes it is not very clear in the UI :) but you can right click on to the "Templates From DB" field and choose "Create FilenameTemplate..." to create a new ``FilenameTemplate``. I should've added a tooltip for that.

**Comment by eoyilmaz** [comment]
Ok I've created the Tooltips for the fields...
