### ISSUE TITLE
Anima pipeline Workflow Q&A

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#23]
Hi I have an issue with files naming system 
- how can I set the default file naming system to the file naming system that I desire?

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
https://pythonhosted.org/stalker/#examples

Erkan Ozgur Yilmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by tws0002** [comment]
Hi, 

Thanks for the reply. Can you give some explanation about Jinja2 for filename in stalker?
I was trying to have a naming like this ep101_s001c001_fxAMain_v01. but I don't know how to make it after all the try!!
![aniamq01](https://user-images.githubusercontent.com/7018625/42198411-7044a3e8-7eba-11e8-9a7d-25960b9e6c09.jpg)
I was trying to name like this ep101_s001c001_fxAMain_v01

Please help 
Desmond

**Comment by tws0002** [comment]
Hi Erkan,
I have tried to fix my file naming system but I not sure if this the correct way to code it. can you give me some advice?
here is my code
```
FT = FilenameTemplate(
    name="Filename_Template",
    target_entity_type="task",
    path='$REPO{{project.repository.id}}/{{project.code}}/{%- for parent_task in parent_tasks -%}{{parent_task.nice_name}}/{%- endfor -%}",
    filename="{% for ep in project.sequences %}{{ep.name}}{% endfor %}_{% for shot in project.shots %}{% set sh = shot %}{% for cut in sh.tasks %}{% set c = cut %}{% for fxsc in c.tasks %}{% for role in fxsc.tasks %}{{sh.name}}{{cut.name}}_{{role.name}}{% endfor %}{% endfor %}{% endfor %}{% endfor %}_{{version.take_name}}_v{{"%02d"|format(version.version_number)}}"
)
```
i found that my code is way too long!!
 
please give advice 
Desmond

**Comment by tws0002** [comment]
Hi Erkan,

I found a bug on Project Dialog about multiple Structure created!!
because I have a few projects created, and I have to assign the specific structure to the specified need.
but it seems not working!! it will assign the same structure for every project. 
do u have this problem?

![anima_q_1](https://user-images.githubusercontent.com/7018625/42872061-74a2d25c-8aae-11e8-86a0-58546ac6ed6e.jpg)

Thanks
Desmond

**Comment by eoyilmaz** [comment]
Aside being long it is not correct. What you are doing is to put all the sequence names of the project side by side and then add all the shot names to is etc.

Here is what you are looking for:

```python
ft = FilenameTemplate(
    name='Filename_Template',
    target_entity_type='Task',
    path='$REPO{{project.repository.id}}/{{project.code}}/{%- for parent_task in parent_tasks -%}{{parent_task.nice_name}}/{%- endfor -%}',
    #filename='{% for ep in project.sequences %}{{ep.name}}{% endfor %}_{% for shot in project.shots %}{% set sh = shot %}{% for cut in sh.tasks %}{% set c = cut %}{% for fxsc in c.tasks %}{% for role in fxsc.tasks %}{{sh.name}}{{cut.name}}_{{role.name}}{% endfor %}{% endfor %}{% endfor %}{% endfor %}_{{version.take_name}}_v{{"%02d"|format(version.version_number)}}',
    filename="""{%- for p in parent_tasks -%}
        {%- if p.entity_type == 'Sequence' -%}
            {{p.name}}
        {%- elif p.entity_type == 'Shot' -%}
            _{{p.name}}{{p.children[0].name}}
        {%- endif -%}
    {%- endfor -%}
    {%- set fx = parent_tasks[-2] -%}
    _{{fx.name}}_{{version.take_name}}_v{{"%02d"|format(version.version_number)}}""",
)
```

**Comment by tws0002** [comment]
Thanks for the advice. 

Question
- Does stalker have entity_type for Episode? for tv series project.

**Comment by eoyilmaz** [comment]
No we generally use ``Sequence`` in place of Episodes, we give names like ``Ep001``.
