### ISSUE TITLE
anima using blender for sequence reviewer?

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#25]
hi, I have a question about blender workflow in anima pipeline.
how to use this `anima.anima.env.blender`?

**Comment by eoyilmaz** [comment]
Around 4 years ago I started writing a Blender plugin which will allow us to add clips to the editor inside Blender. But the tool is newer completed.

Recently, I'm very excited about the addition of Python to DaVinci Resolve and I probably use it instead of Blender.

**Comment by tws0002** [comment]
meaning you are not releasing blender version to anima pipeline for now?

**Comment by eoyilmaz** [comment]
yes I'm not

**Comment by tws0002** [comment]
ok thx
