### ISSUE TITLE
How To Install Anima library!

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#4]
hi do you provide a documentation for anima setup ?
because i have problem when using anima and stalker in maya python!! 

here is the error 
import stalker
# Error: line 1: ImportError: file <maya console> line 1: No module named stalker # 
import anima
# Error: line 1: ImportError: file <maya console> line 1: No module named anima #

**Comment by eoyilmaz** [comment]
They should exist in a folder that is added in the PYTHONPATH environment variable

**Comment by tws0002** [comment]
yup it should be!! 
when i using cmd python it work fine 
but when using in maya python, this error pop out !!

**Comment by tws0002** [comment]
can i ask is it anima is the upgrade version of oyProjectManager ?

because when i try using oyProjectManager this error come out !!

>>> import oyProjectManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\oyprojectmanager-0.2.5.3-py2.7.egg\oyProjectManager\__init__.py", line 26, in <module>
    from oyProjectManager.models.asset import Asset
  File "C:\Python27\lib\site-packages\oyprojectmanager-0.2.5.3-py2.7.egg\oyProjectManager\models\asset.py", line 12, in <module>
    from oyProjectManager.models.entity import VersionableBase
  File "C:\Python27\lib\site-packages\oyprojectmanager-0.2.5.3-py2.7.egg\oyProjectManager\models\entity.py", line 16, in <module>
    from oyProjectManager.models.version import Version
  File "C:\Python27\lib\site-packages\oyprojectmanager-0.2.5.3-py2.7.egg\oyProjectManager\models\version.py", line 33, in <module>
    class VersionStatusComparator(str, Comparator):
TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict

do you have any idea? 
i really like the pipeline u share!! but don't know how to setup!! 
i hope can learn from the workflow you share.

**Comment by tws0002** [comment]
hi eoylimaz, really hope you can give me some help. Thanks

**Comment by eoyilmaz** [comment]
Hi again,

Sorry for my late reply. I'm updating the **About** page to also include the installation instructions.

**Comment by eoyilmaz** [comment]
Ok it's done, I've updated the about page (based on a recent email to a similar question!), hope it will help.

**Comment by tws0002** [comment]
Thanks for the help.
But I haveing some problem when doing login!!! 
This error popup when I run the script 

# Traceback (most recent call last):
#   File "\Library\anima\anima\ui\login_dialog.py", line 95, in login
#     .filter(or_(User.login == login, User.email == login)) \
#   File "build\bdist.win32\egg\sqlalchemy\orm\query.py", line 2697, in first
#   File "build\bdist.win32\egg\sqlalchemy\orm\query.py", line 2489, in __getitem__
#   File "build\bdist.win32\egg\sqlalchemy\orm\query.py", line 2797, in __iter__
#   File "build\bdist.win32\egg\sqlalchemy\orm\query.py", line 2820, in _execute_and_instances
#   File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 945, in execute
#     
#   File "build\bdist.win32\egg\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
#   File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
#     
#   File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1189, in _execute_context
#     
#   File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
#     
#   File "build\bdist.win32\egg\sqlalchemy\util\compat.py", line 202, in raise_from_cause
#   File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1182, in _execute_context
#     
#   File "build\bdist.win32\egg\sqlalchemy\engine\default.py", line 469, in do_execute
# sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type. [SQL: u'SELECT "Users".id AS "Users_id", "Entities".id AS "Entities_id", "SimpleEntities".stalker_version AS "SimpleEntities_stalker_version", "SimpleEntities".id AS "SimpleEntities_id", "SimpleEntities".entity_type AS "SimpleEntities_entity_type", "SimpleEntities".name AS "SimpleEntities_name", "SimpleEntities".description AS "SimpleEntities_description", "SimpleEntities".created_by_id AS "SimpleEntities_created_by_id", "SimpleEntities".updated_by_id AS "SimpleEntities_updated_by_id", "SimpleEntities".date_created AS "SimpleEntities_date_created", "SimpleEntities".date_updated AS "SimpleEntities_date_updated", "SimpleEntities".type_id AS "SimpleEntities_type_id", "SimpleEntities".generic_text AS "SimpleEntities_generic_text", "SimpleEntities".thumbnail_id AS "SimpleEntities_thumbnail_id", "SimpleEntities".html_style AS "SimpleEntities_html_style", "SimpleEntities".html_class AS "SimpleEntities_html_class", "Users".email AS "Users_email", "Users".password AS "Users_password", "Users".login AS "Users_login", "Users".efficiency AS "Users_efficiency", "Users".rate AS "Users_rate" \nFROM "SimpleEntities" JOIN "Entities" ON "SimpleEntities".id = "Entities".id JOIN "Users" ON "Entities".id = "Users".id \nWHERE "Users".login = ? OR "Users".email = ?\n LIMIT ? OFFSET ?'] [parameters: (PyQt4.QtCore.QString(u'spdes'), PyQt4.QtCore.QString(u'spdes'), 1, 0)]

I think is user setup problem!! 
I follow the instruction u provide, but I don't know where to find the data setup file for User and studio setting!! 

Thanks
Desmond

**Comment by eoyilmaz** [comment]
The first line on the instruction says "use a PostgreSQL" database :), and
as I see you are using SQLite3. Try to switch it to PostgreSQL and try again

Erkan Ozgur Yilmaz

**Comment by tws0002** [comment]
thanks for the quick reply .

meaning i need to uninstall SQLight3?

Desmond

**Comment by eoyilmaz** [comment]
No you don't need to uninstall SQLite3 but install a propet PostgreSQL
database from: https://www.postgresql.org/download/

P.S.: I presume that you are using Windows as your OS.

On Dec 30, 2016 14:27, "Desmond" <notifications@github.com> wrote:

thanks for the quick reply .

meaning i need to uninstall SQLight3?

Desmond

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/eoyilmaz/anima/issues/4#issuecomment-269761175>, or mute
the thread

**Comment by tws0002** [comment]
yes I'm using window. i do insall PostgreSQL in my system!! but when i run the script it point to SQLite3!! not sure why !! 
but stalker is using SQLAlchemy right? 

Desmond

**Comment by tws0002** [comment]
is it i need to change this 

database_engine_settings={
    "postgresql.url": "postgresql://user:password@address/db_name",
    "postgresql.echo": False
}

instead of this 

database_engine_settings={
    "sqlalchemy.url": "postgresql://user:password@address/db_name",
    "sqlalchemy.echo": False
}

Desmond

**Comment by tws0002** [comment]
here is another problem. pyside seem like not working!! if i change pyside to pyqt4 everything is loaded!! so not sure whats the error is!! same error on maya 2016 and 2017!! 

from stalker import db
db.setup()

from anima.ui.scripts import maya
maya.version_creator()
# Warning: stalker.config : The $STALKER_PATH: \Library\Setting	\config.py doesn't exists! skipping user config # 
# stalker.db : no settings given, using the default: {'sqlalchemy.echo': False, 'sqlalchemy.url': 'sqlite:///:memory:'} # 
# stalker.db : settings: {'sqlalchemy.echo': False, 'sqlalchemy.url': 'sqlite:///:memory:'} # 
# stalker.db : engine: Engine(sqlite:///:memory:) # 
# stalker.db : current_alembic_version: None # 
# stalker.db : creating the tables # 
# pymel.core : Updating pymel with pre-loaded plugins: mayaHIK, GamePipeline, CloudImportExport, tiffFloatReader, bifrostvisplugin, studioImport, ikSpringSolver, ik2Bsolver, xgenToolkit, AbcExport, retargeterNodes, gameFbxExporter, VectorRender, AutodeskPacketFile, OpenEXRLoader, Unfold3D, mayaCharacterization, modelingToolkit, MayaMuscle, rotateHelper, redshift4maya, DirectConnect, matrixNodes, AbcImport, BifrostMain, autoLoader, Substance, shaderFXPlugin, bifrostshellnode, ArubaTessellator, quatNodes, fbxmaya # 
xgmNurbsPatch [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmPatch', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmNurbsPatch']
# Warning: pymel.internal.apicache : lineage for node xgmNurbsPatch is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmPatch', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmNurbsPatch'] # 
xgmSubdPatch [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmPatch', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSubdPatch']
# Warning: pymel.internal.apicache : lineage for node xgmSubdPatch is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmPatch', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSubdPatch'] # 
xgmArchiveGuide [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmArchiveGuide']
# Warning: pymel.internal.apicache : lineage for node xgmArchiveGuide is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmArchiveGuide'] # 
xgmCardGuide [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmCardGuide']
# Warning: pymel.internal.apicache : lineage for node xgmCardGuide is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmCardGuide'] # 
xgmSphereGuide [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSphereGuide']
# Warning: pymel.internal.apicache : lineage for node xgmSphereGuide is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSphereGuide'] # 
xgmSplineGuide [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSplineGuide']
# Warning: pymel.internal.apicache : lineage for node xgmSplineGuide is cyclical: [u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmGuide', u'containerBase', u'entity', u'dagNode', u'shape', u'geometryShape', u'deformableShape', u'controlPoint', u'surfaceShape', u'THsurfaceShape', u'xgmSplineGuide'] # 
IS_PYQT4(): False
IS_PYSIDE(): True
IS_PYSIDE2(): False
# anima : importing PySide # 
# Error: ImportError: file \Library\anima\anima\ui\lib.py line 24: DLL load failed: %1 is not a valid Win32 application. # 

Desmond

**Comment by eoyilmaz** [comment]
I've just updated the code to work with Maya 2017, so merge ghe new changes

**Comment by tws0002** [comment]
Happy New Year eoyilmaz!! 
I will try the new update when I in office!! 

Desmond

**Comment by tws0002** [comment]
Thanks for the help. 

it work for maya 2016 now. after this how can I intergrade my pipeline with anima? 
how do you add task, project, management and etc in anima?
have any interface like "TACTIC/SHOTGUN" to manage task and schedule? 

Desmond

**Comment by eoyilmaz** [comment]
The GUI is called ``Stalker_Pyramid`` is **OpenSource** but have dependencies to closed source files, in which we're in progress of removing them, and we do not distribute it for now. I was expecting to release it these days, but it is taking time, because we're also converting the backend to a full **RESTFul** service and upgrading the front end to **Angular.js**. It will probably be released in this summer.

But, you can write your own interfaces with ``PySide/PySide2`` and this is the intended way of using ``Stalker``, ``Anima``, ``Stalker_Pyramid`` on the way of building your own pipeline.

For now you should read the [Stalker Documentation](http://pythonhosted.org/stalker/) and get familiar with it.

**Comment by tws0002** [comment]
Hi thanks for the help. 
I'm quite new on coding!! So can you give me some advice?
because i have to create user, task and etc everytime when i start anima!! i think it should be save all the data in a database.
I'm not sure how to create a database for studio!! not sure how to start the db server and how should i load the database!! 
in stalker u are using sqlite but in anima postgresq. What the different between this 2 database?

Thanks 
Desmond
