### ISSUE TITLE
how to use anima pipeline in Nuke and Houdini?

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#8]
Hi,

May I ask how to use anima pipeline in Nuke and Houdini?
is it ready for this 2 software? 
do you plan to create a documentation for anima pipeline?

Thanks
Desmond

**Comment by eoyilmaz** [comment]
For Houdini create a new shelf, then add a new tool to that shelf, right click on the tool icon and write the following code in the script tab:

```python
from anima.ui.scripts import houdini
houdini.version_creator()
```

We are not using Nuke in our studio. But the process is similar:

```python
from anima.ui.scripts import nuke
nuke.version_creator()
```

For the documentation, it's hard. I didn't write the code to include extensive documentation. But I can answer your questions.

Although the library has a lot of generic code, it is very much tailored to our workflow in the studio. But it is a nice tool and we have completed a feature movie project with it and still using it on our commercial projects.

**Comment by tws0002** [comment]
Thanks for the quick reply!!
Maybe you can do a video tutorial to introduce anima pipeline? ("just a suggestion")
Can anima be a standalone python app use for project management purpose? 
I have a big problem when working on PostgreSQL database!! not sure how to manage the DB for anima!! is there have any tools for me to manage project task, user, and project schedule?
because of i not familiar with database!! hope you can help me on this part. 

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
Our generic Task structure for a Feature Film Project is as follows:

```
Project (Project)
+- Assets (Task)
|  +- Characters (Task)
|  |  +- {CharacterName} (Asset | Type.name = "Character")
|  |  |  +- Model (Task | Type.name = "Model")
|  |  |  +- LookDev (Task | Type.name = "Look Development") >------------------------------------+
|  |  |  +- Rig (Task | Type.name = "Rig") >-----------------------------------------------------|-+
|  +- Environments (Task)                                                                        | |
|  |  +- Exteriors                                                                               | |
|  |  |  +- {EnvironmentName} (Asset | Type.name = "Exterior")                                   | |
|  |  |  |  +- {BuildingName} (Asset | Type.name = "Building")                                   | |
|  |  |  |  |  +- Layout (Task | Type.name = "Layout")  <------------------+-+ >-+               | |
|  |  |  |  |  +- LookDev (Task | Type.name = "Look Development")          | |   |               | |
|  |  |  |  |  +- Props (Task)                                             | |   |               | |
|  |  |  |  |  |  +- YAPI (Task)                                           | |   |               | |
|  |  |  |  |  |  |  +- Model (Task | Type.name = "Model")                 | |   |               | |
|  |  |  |  |  |  |  +- LookDev (Task | Type.name = "Look Development")  >-+ |   |               | |
|  |  |  |  |  |  +- {PropName} (Asset | Type.name = "Prop")                 |   |               | |
|  |  |  |  |  |  |  +- Model (Task | Type.name = "Model")                   |   |               | |
|  |  |  |  |  |  |  +- LookDev (Task | Type.name = "Look Development") >----+   |               | |
|  |  |  |  +- Layout (Task | Type.name = "Layout")  <---------------------------+ >-+-+         | |
|  |  |  |  +- LookDev (Task | Type.name = "Look Development")  <--------------------+ | <-+     | |
|  |  +- Interiors                                                                     |   |     | |
|  |  |  +- {EnvironmentName} (Asset | Type.name = "Interior")                         |   |     | |
|  |  |  |  +- (Same as an Exterior)                                                   |   |     | |
|  +- Props (Task)                                                                     |   |     | |
|  |  +- {PropName} (Asset | Type.name = "Prop")                                       |   |     | |
|  |  |  +- Model (Task | Type.name = "Model")                                         |   |     | |
|  |  |  +- LookDev (Task | Type.name = "Look Development") >--------------------------|---+     | |
|  +- Vehicles (Task)                                                                  |         | |
+- Sequences (Task)                                                                    |         | |
   +- {SequenceName} (Sequence)                                                        |         | |
      +- Edit (Task)                                                                   |         | |
      +- Previs (Task | Type.name = "Previs")                                          |         | |
      +- Scenes (Task)                                                                 |         | |
         +- {SceneName} (Task | Type.name = "Scene")                                   |         | |
            +- Shots (Task)                                                            |         | |
               +- {ShotName} (Shot)                                                    |         | |
                  +- Animation (Task | Type.name = "Animation") <----------------------+  <------|-+ <-+
                  +- Previs (Task | Type.name = "Shot Previs") >-----------------------|---------|-----+
                  +- Camera (Task | Type.name = "Camera") >----------------------------|------+  |
                  +- Comp (Task | Type.name = "Comp")                                  |      |  |
                  +- Lighting (Task | Type.name = "Lighting") <------------------------|---+  | <+
                  +- Plate (Task | Type.name = "Plate")                                |   |  |
                  +- Scene Assembly (Task | Type.name = "Scene Assembly")  <-----------+ >-+ <+
```
I've tried to show here the file references. For example the Maya file references that is. Then it got very complex to simply show it here. So I explained the pipeline below.

**Character Pipeline**
Basically for assets (or anything that has a rig, ex. ``Active Props``, ``Characters`` or ``Vehicles``) we reference the ``Model`` of an ``Asset`` to its ``Look Dev``, reference the ``Model`` to ``Rig`` and reference the ``Rig`` to the ``Animation`` task of a ``Shot``.

For ``Animation`` tasks we reference the ``Rig`` of the ``Characters`` and ``Active Props`` to the ``Animation`` task of a ``Shot`` and also reference the ``GPU take`` (explained below) to the ``Animation``, so the animator is able to see the hires environment without having a big impact in the performance.

Then when the ``Animation`` file is published an ``Alembic`` file is generated automatically per character, which are referenced to ``Scene Assembly`` tasks of ``Shots``. The cache files doesn't contain any shading information.  So when we reference the ``Scene Assembly`` to the ``Lighting`` of a ``Shot`` we also reference the ``Look Dev`` files to that ``Shot``. A custom script (in ``anima.env.mayaEnv.auxiliary``) assigns the shaders from the referenced ``LookDev`` files to the referenced alembic caches of the ``Characters/Active Props``. Then we add lights and render the shot. The render output is then used in the ``Comp`` task and the outputs are gathered in the editors timeline (Avid or Resolve).

**Environment Pipeline**
For environments, we reference the ``Look Dev`` of ``Props`` (stationary objects) to the ``Layout`` of a ``Building`` or to the ``Layout`` of an ``Environment (Exterior/Interior)``.

The ``Model`` of the building is referenced to ``Look Dev`` of the building, then the ``Look Dev`` is referenced to the ``Layout`` of the container ``Exterior/Interior`` task. Then when the ``Layout`` is published an ``Arnold Scene Source (ASS)`` a ``Redshift Proxy (RS)`` and a ``GPU Alembic (GPU)`` is automatically generated *as a take* for that ``Layout`` task (with the take names of ``ASS``, ``RS`` and ``GPU`` respectively). These secondary scene files have all their references imported. But the ``Main`` take of the Layout **still has everything as referenced**.

All these automation is done by the ``anima.publish`` and ``anima.env.mayaEnv.publish`` files. There are two types of ``Publishers``, ``PRE_PUBLISHER`` and ``POST_PUBLISHER``. The ``PRE_PUBLISHER``s check the file quality according to its task type. For example it checks if every model have a proper UV for a ``Model`` task, and checks if every object in a ``LookDev`` scene have a proper shader (other than lambert1) and tons of other things. The ``POST_PUBLISHER``s generally do the automated exports. For example it creates the Alembic caches when a maya file is published under an  ``Animation`` task, and creates and uploads the playblast to the ``Stalker_Pyramid`` server so we can watch them in ``Dailies``.

**Shot Pipeline**
Actually the shot pipeline is explained in the **Character** and **Environment** pipelines. But to gather the information here I'll explain it again. Our Previs artist works on the ``Previs`` task under the ``Sequence``. Then after exporting and importing the edit (EDL or XML files) a tons of times with the editor (which works with the Director in Avid or Resolve) he/she creates the Shots in Maya's Sequencer and decides  the ``in`` and ``out`` ranges for a particular ``Shot``. This is a fairly automated process. The Previs artist exports EDL/XML files to the Editor. The Editor may split or delete the shots, Then the Editor exports the EDL/XML files back to the Previs artist. Then the Previs artist can conform these EDL/XML files in Maya Sequencer. And then the Previs artist gives the final ``Shot`` names and exports the previs animation to the ``Previs`` task to a particular ``Shot``.

Then the Animator references this ``Shot Previs`` file in to its ``Animation`` scene and references all the required ``Assets`` (hopefully we now have an automated script for that, which is looking at the Task.depends attribute and finds the required assets). Then when the Animator finishes his/her work, he/she publishes the ``Animation`` file which in return generates the Alembic caches, exports the playblast to ``Dailies`` and creates a new EDL/XML (if the Animator decided to cut or extend the shot for a couple of frames the Editor knows the edit), exports the scene camera to ``Camera`` task under the ``Shot`` so we know if the animator has retouched the camera according to his/her animation.

Then another artist gathers everything in the ``Scene Assembly`` task. He/she references the alembic caches from ``Animation``, references the ``Camera`` references the ``Environment (GPU)``. At this stage everything in the Maya scene is in gray (doesn't have any shaders that is). Then it generates a new movie clip, showing the edit of the ``Scene`` (a ``Scene`` is a container for ``Shot``s and a ``Sequence`` may have more than one ``Sceene``).

It everything works well and the Director approves the ``Scene`` edit. Then a lighting artist references the ASS/RS take of the ``Scene Assembly`` file to his/her ``Lighting`` scene and also references all the ``LookDev`` files of ``Assets`` (which at this point are alembic caches without any shading information). then creates the necessary lighting and renders the scene (with preview quality). And then after all the ``Shot``s in a ``Scene`` is rendered (with preview quality again) he/she submits the scene for review to the Director. If the Director approves the ``Scene`` then the lighting artist(s) render the shots in final quality. The lighting artist is also responsible of the ``Comp`` task.

All this deep file referencing helps us use the resources more efficiently and keep track of a good amount of data. All of the ``Model``, ``Look Development`` and ``Layout`` tasks have the automatically generated ASS/RS/GPU takes. The ``Layout`` task can only contain other ``Layout`` tasks or ``Look Development`` files. And when a ``Look Development`` file is referenced to a ``Layout`` and the ``Layout`` is published, all of the references are replaced with their secondary takes (ASS/RS/GPU) for the ASS/RS/GPU takes of the ``Layout`` task. The secondary takes (ASS/RS/GPU) of an upper most ``Layout`` task in an environment have every references imported to make it easy to reference in to the ``Scene Assembly`` and ``Animation`` tasks. But again the ``Main`` take of the ``Layout`` has the references so we can track the assets.

Also we use the Task Status Workflow in Stalker. But it is so huge that I should explain it in another post/article.

Here I tried to summarize our Feature Film pipeline in the studio. There are tons of other details. This information should lead you, at least should make it a little bit clear.

On the other hand for our Commercial Projects, the task structure is generally the same, but we reduced the amount of tasks on the ``Shots`` for example. So there is no ``Shot Previs`` task or a ``Scene Assembly`` in a Commercial Project.

**And I would like to state that this is my answer to those hiding the information. Years ago when I started to build this pipeline nobody was giving any information, hiding behind their NDAs. As an answer to them I OpenSourced my work and will always share what I know with rest of the world.**

**So ask me anything!**

**Comment by eoyilmaz** [comment]
If by *manage* you mean creating Projects, Tasks etc. you shouldn't do it over the database directly. Use the Python API. Recently I've created UI's for Project\Task management in ``anima``. Check the ``anima.ui`` folder.

The Project management is done over Stalker Pyramid in our Studio (or they try to do it at least). But again you can use the ``anima.ui`` and create your own PySide/PySide2/PyQt4/PyQt5 UIs.

**Comment by tws0002** [comment]
thanks for the explanation of anima. I will try to test this on asap.
can I ask about how is the simulation and FX workflow handle by anima?
how are Maya and Houdini share animation, shader and lighting file? 
anima support for Maya 2015.6?

**Comment by eoyilmaz** [comment]
Oh yes I forgot to add the FX pipeline. Every Shot that has an ``FX`` task, we do the FX in Houdini and export the data either with ``Alembic`` files or with ``ASS/RS`` proxies and import the data to ``Scene Assembly``. We do not share any shading info between Houdini and Maya other than some custom point attributes.

And although we directly switched to Maya 2017 from Maya 2014, ``anima`` should support Maya 2015.

**Comment by tws0002** [comment]
Hi, 

from anima.ui.scripts import maya
maya.version_creator()

# Error: ImportError: file K:\SES\Library\anima_pipe\anima\anima\ui\lib.py line 20: DLL load failed: %1 is not a valid Win32 application. #

I having problem `from PySide import QtCore, QtGui, QtWidgets`!!
so I using https://github.com/mottosso/Qt.py
So instead of PySide, I change it to `from Qt import QtCore, QtGui, QtWidgets`. So what do u think?

but now I having this problem 
# Error: KeyError: file C:\Python27\Lib\site-packages\stalker\config.py line 96: version_take_name # 
do u have any idea on this?

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
First, I need a full stack trace for the error message.
Secondly what Stalker version did you install?

**Comment by eoyilmaz** [comment]
I've added support for Qt.py. To be able to use it you should set your ``QT_LIB`` environment variable to ``QTPY`` (preferably in a ``userSetup.py`` file which Maya picks and run).

**Comment by tws0002** [comment]
Thanks for the change!! 
I create a bat file to launch Maya.
here is the bat 
```

echo -----------------------------------------------------------
set STALKER=C:\Python27\Lib\site-packages
set ANIMA=K:\SES\Library\anima_pipe\anima
set STALKER_CONFIG=K:\SES\Library\anima_pipe\setting
set QT=K:\SES\Tools\Qt.py
set Python=C:\Python27\Lib\site-packagess
set jinja2=K:\SES\Library\anima_pipe\jinja
set markupsafe=K:\SES\Tools\markupsafe
set pytz=K:\SES\Tools\pytz

set PYTHONPATH=%ANIMA%;%STALKER%
set %QTPY%=%QTPY%;%QT%
set STALKER_PATH=%STALKER_PATH%;%STALKER_CONFIG%
set MAYA_SCRIPT_PATH=%MAYA_SCRIPT_PATH%;%ANIMAPATH%\anima\env\mayaEnv\config;

"c:\program files\autodesk\maya2017\bin\maya.exe"

```

Now I having the problem of this 
```
from anima.ui.scripts import maya
maya.version_creator()

# Error: ImportError: file K:\SES\Library\anima_pipe\anima\anima\ui\utils.py line 12: cannot import name QtCore # 
```
seems like there is a conflict with QT!!

**Comment by tws0002** [comment]
Here is the stalker detail from my site
```
stalker.__file__
# Result: C:\Python27\Lib\site-packages\stalker\__init__.pyc # 
stalker.__version__
# Result: 0.2.21 # 
```
Here is the error when i execute in maya 
```
from stalker import db
db.setup()
db.init()
# Warning: stalker.config : The $STALKER_PATH: ;K:\SES\Library\anima_pipe\setting\config.py doesn't exists! skipping user config # 
```

**Comment by eoyilmaz** [comment]
Can we close this issue now

**Comment by tws0002** [comment]
Yes. i will close it
